# Generated by Django 5.2.6 on 2025-09-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cooking_area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type',
        ),
    ]
